version: '3.8'

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminsecretkey
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio:/data

#  minio-init:
#    image: minio/mc:latest
#    command:
#      - mc config host add --insecure local_minio http://minio:9000 admin adminsecretkey &&
#        mc mb -p local_minio/forge &&
#        mc mirror --overwrite /data local_minio/forge
#    entrypoint: [ "/bin/sh", "-c" ]
#    depends_on:
#      - minio
#    volumes:
#      - ../datasources/:/data

volumes:
  minio: